### PR TITLE
Error because of concatenation in property.

### PR DESCRIPTION
**Pull request by aavrug**

### CODE REVIEW

**Comment by clthck** [comment]
@aavrug are you willing to be an active maintainer of this repo?

**Comment by aavrug** [comment]
@clthck Yea sure.

**Comment by clthck** [comment]
Cool. I'll invite you to the repo. I suggest to change the repo name to `cakephp-pug`, as Jade is officially renamed to Pug. Also, it uses [tale-jade](https://github.com/Talesoft/tale-jade), I [contacted](https://github.com/Talesoft/tale-jade/issues/129) author of tale-jade and he recommended to check out [Phug](https://github.com/phug-php).

**Comment by aavrug** [comment]
Thanks for adding, I was busy in attending the #pycon so I have just started working on it. Could you please send me your mail so I can directly contact you or are you on slack, IRC?

**Comment by clthck** [comment]
can you let me know your skype handle?

**Comment by aavrug** [comment]
undefined61

**Pull request merged**
